server:
  port: 8100
spring:
  application:
    name: dubbo-stock-example
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/seata?useSSL=false&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    username: root
    password: root
dubbo:
  scan:
    base-packages: io.seata.samples.integration
  application:
    id: dubbo-stock-example
    name: dubbo-stock-example
    qosEnable: false
  protocol:
    id: dubbo
    name: dubbo
    port: 20882
  registry:
    id: dubbo-stock-example-registry
    address: nacos://127.0.0.1:8848
    check: false
  consumer:
    check: false
management:
  endpoints:
    web:
      exposure:
        include: '*'
mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml
